apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate"
  labels:
    app: {{ template "chatwoot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": {{ .Values.hooks.migrate.hookAnnotation }}
    "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init-postgres
        image: busybox:1.28
        command: ["sh", "-c",  "until nslookup {{ .Values.env.POSTGRES_HOST }}; do echo waiting for {{ .Values.env.POSTGRES_HOST  }}; sleep 2; done;"]
      - name: init-redis
        image: busybox:1.28
        command: ["sh", "-c", "until nslookup {{ .Values.env.REDIS_HOST }}; do echo waiting for {{ .Values.env.REDIS_HOST  }}; sleep 2; done;"]
      containers:
      - name: "db-migrate-job"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bundle
        - exec
        - rails
        - db:chatwoot_prepare
        env:
            {{- include "chatwoot.environ" .  }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
