apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-migrate"
  labels:
    app: {{ template "chatwoot.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": {{ .Values.hooks.migrate.hookAnnotation }}
    # "helm.sh/hook-delete-policy": "hook-succeeded,before-hook-creation"
    "helm.sh/hook-weight": "-1"
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
      - name: init-wait
        image: busybox:1.28
        command: ["sh", "-c",  "sleep 120"]    
      - name: init-postgres
        image: busybox:1.28
        command: ["sh", "-c",  "until nslookup {{ template "chatwoot.postgresql.host" . }} ; do echo waiting for {{ template "chatwoot.postgresql.host" . }}; sleep 2; done;"]
      - name: init-redis
        image: busybox:1.28
        command: ["sh", "-c", "until nslookup {{ template "chatwoot.redis.host" . }} ; do echo waiting for {{ template "chatwoot.redis.host" . }} ; sleep 2; done;"]
      containers:
      - name: "db-migrate-job"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - bundle
        - exec
        - rails
        - db:chatwoot_prepare
        envFrom:
          - configMapRef:
              name: {{ template "chatwoot.fullname" . }}-env
        imagePullPolicy: {{ .Values.image.pullPolicy }}
