apiVersion: v2
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 10.5.3
  - condition: redis.enabled
    name: redis
    repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
    version: 14.7.2
name: chatwoot
description: Open-source customer engagement suite, an alternative to Intercom, Zendesk, Salesforce Service Cloud etc. ðŸ”¥ðŸ’¬
type: application
keywords:
  - chatwoot
  - open source
  - customer support
  - chat
  - ruby
  - rails
  - crm
maintainers:
  - name: vishnu-narayanan
    email: vishnu@chatwoot.com
  - name: sojan-official
    email: sojan@chatwoot.com
home: https://github.com/chatwoot/charts
icon: https://chatwoot-public-assets.s3.amazonaws.com/logo/square.png
sources:
  - https://github.com/chatwoot/chatwoot
  - http://www.chatwoot.com

# This is the chart version.
version: 0.9.0

# This is the application version.
appVersion: "v2.7.0"
